global:
  scrape_interval:     5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dockerswarm-sd'

    # stop Prom for mangling the labels by adding "exported_" prefix
    honor_labels: true

    file_sd_configs:
    - files:
      - '/etc/prometheus/targets-from-swarm.json'
